#!/sbin/sh
export PATH=/sbin:/bin:/usr/bin:/usr/sbin
# install symlinks for all of the suppoted utilities
# install busybox symbolic links
/sbin/busybox --install -s
#
[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir --mode=0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
#
mount -t sysfs none /sys -onodev,noexec,nosuid
mount -t proc none /proc -onodev,noexec,nosuid
#
mknod /dev/zero c 1 5
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mknod /dev/console c 5 1
mknod /dev/ptmx c 5 2
mknod /dev/tty0 c 4 0
mknod /dev/tty1 c 4 1
# initial population and dynamic updates
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
/sbin/mdev -s
# not-so-traditional init procedure :P

#mount efiesp and save dmesg
mkdir /efiesp
mount -t vfat /dev/mmcblk0p25 /efiesp
dmesg > /efiesp/dmesg.log
ls -l /dev > /efiesp/dev.lst
#libaroma
/usr/bin/libaroma /usr/bin/res.zip>/efiesp/aroma.log
#unmount efiesp when libaroma exited
umount /efiesp
#exec /sbin/sh
